### ISSUE TITLE
On the welcome page replace "LosFuzzys" with our current logo in front: "(logo) LosFuzzys"

### ISSUE THREAD

**Issue by kaydoubleu** [LosFuzzys/CTFd#10]
![losfuzzys_logo_06_final](https://cloud.githubusercontent.com/assets/1720809/24839593/d2faf5ce-1d5d-11e7-8a45-1e6363e9edb6.jpg)

**Comment by stefan2904** [comment]
We just talked about this, and agreed on not replace the logo, but instead remove the LosFuzzys from the CTF logo (just the bug then), and maybe add a small losfuzyzs logo to the footer.

**Comment by kaydoubleu** [comment]
* [x] Updated the logo for Fuzzy Land
* [ ] Replace text "LosFuzzys" with a little version of our logo "(logo) LosFuzzys"
