### ISSUE TITLE
Add license text of our logos (Fuzzy Land and Los Fuzzys) visible below them

### ISSUE THREAD

**Issue by kaydoubleu** [LosFuzzys/CTFd#11]
Sth like:

---
The logo for "Fuzzy Land" and "Los Fuzzys" can be used for any legal purpose under three conditions:
1. The logos' author must be attributed by name & link to his web site; Thomas Mayr (thomay.at).
2. It must be mentioned that this is a logo in the context of "Fuzzy Land" or "Los Fuzzys", depending on the used logo.
3. The text for the two aforementioned points must be put visible on the same page/area as where the logo is put. <br>
If you are not sure how to add one of our logos to your article, web page, etc., contact us ;)
---

Would you add/edit sth?

**Comment by stefan2904** [comment]
I am not sure about Markenrechte & effects on logos, but maybe just do

* https://creativecommons.org/choose/
* --> https://creativecommons.org/licenses/by-nd/4.0/

**Comment by kaydoubleu** [comment]
Ok, after a discussion with @stefan2904 we decided to put instead a copyright on our logos/symbols.
So, sth like:
---
Logo(s) designed by Thomas Mayr (thomay.at), copyright by LosFuzzys. 
---

**Comment by stefan2904** [comment]
so cc allows everyone to use it as long as they attribute it to us, even commercially. 
and marken-/logo-rechte forbid to use it as other team's logo, I suppose, but i am not sure.

**Comment by kaydoubleu** [comment]
@stefan2904 nice links! So:

---

LosFuzzys Logo by [Thomas Mayr](thomay.at) is licensed under a Creative Commons Attribution-NoDerivatives 4.0 International License. If any changes of the logo are made, sharing/distribution of the adapted work is not allowed.

---

**Comment by kaydoubleu** [comment]
So, currently our copyright text:
CTF operated by LosFuzzys. Infrastructure sponsored by netcup. Logo by Thomas Mayr. All tasks and writeups are copyrighted by their respective authors. 

---

Similar as on [https://ctftime.org/](CTFTime).
