### ISSUE TITLE
Replace "Team" by "User" everywhere

### ISSUE THREAD

**Issue by stefan2904** [LosFuzzys/CTFd#15]
At the moment, fuzzy land talks about "Teams" everywhere. Since we are a person (individual) ctf and not a team ctf, I propose to change "Team" to "Discoverer" or "Player" or "Hacker" or "User", or similar. 

Replacing it in the template should be enough,
I dont think we should touch the database models etc.

**Comment by stefan2904** [comment]
Any opinion on this?

**Comment by skogler** [comment]
Replaced strings in the theme in b17fe27. URLs remain the same for now.
