### ISSUE TITLE
Implement executable challenge type

### ISSUE THREAD

**Issue by skogler** [LosFuzzys/CTFd#18]
A request for use in courses was to add a new challenge type where users need to submit a file instead of a flag. This file should then be passed to a challenge script that runs it within a container and returns whether the submission was valid. The container needs to be isolated from the internet for this.

This could also be used by us for some PPC challenges where we want users to hand-craft executables for weird processor types or implement some other type of code.

**Comment by stefan2904** [comment]
#yolo ?

**Comment by stefan2904** [comment]
Maybe isolate by moving to a raspberry pi that has /root mounted ro and a ramfs and reset it after each run, or something like this? 😛

**Comment by f0rki** [comment]
we're giving people free shells with every pwning challenge... running submitted programs is not more dangerous in any way :P 

I think for this we need a base image that has a service running that allows to submit arbitrary files and run a custom testrunner script.

The question is on how to isolate the provided program. We could in theory run docker inside the challenge docker container to start unprivileged containers. The caveat of this is that we'd have to make the challenge container privileged aka. root. All other challenges run as unprivileged containers, which means we only have to trust challenge authors in a rather limited way... 

What we could do is the following: Create a trusted privileged docker container for each ppc challenge, which runs a nested docker instance. The the challenge author provides
1. one or multiple Dockerfile(s) with the validation service 
2. one Dockerfile specifying the container in which the submitted binaries run

The question is on how the validation service would talk to the privileged container for launching docker container...

**Comment by stefan2904** [comment]
michi hosted the challenges on his machine so we wont need this right now.
