### ISSUE TITLE
Add challenge tagging and highlighting for university courses

### ISSUE THREAD

**Issue by skogler** [LosFuzzys/CTFd#19]
A request for use in courses was to be able to tag challenges, which would then be highlighted somehow. They could also be on a separate listing page or something like that.

Tagging should already work in CTFd, this is probably just a theming issue.

**Comment by stefan2904** [comment]
I tagged the two *abc* challenges with *intro* to test this.
The tags are displayed if you click on the challenge, but not in the overview.
Furthermore, I dont see a option to search for challenges by tag?

Maybe this is just a model for tags, and we need to utilize this via a plugin?

**Comment by stefan2904** [comment]
What would be cool:

* Tag challenges, for example *SASE* --> already possible
* Display tag in overview or filter by tag in overview
* course specific highscore, 2 options:
  * Tag specific highscore (like normal scoreboard but only count challenges with specific tag), or
  * Implement groups (invite only or manual add for lectures) --> only count people in group,
  * A combination of those two (only count *SASE* challenges and only display people in *SASE* group)

**Comment by skogler** [comment]
CSAW did something quite cool with this tagging feature:

![1506031736](https://user-images.githubusercontent.com/1032405/30721027-50da58f6-9f2a-11e7-8611-13863db9c917.png)

**Comment by stefan2904** [comment]
The filter on the top? Nice, yes.

Also, I like the design in general. :)

**Comment by stefan2904** [comment]
challenge tagging is implemented but it is not possible to filter right now. #13 might be relevant for that.

challenge category colors are possible via edits to the css sheets.
