### ISSUE TITLE
Stats

### ISSUE THREAD

**Issue by kaydoubleu** [LosFuzzys/CTFd#2]
URL suggestion: stats.losctf.. (à la subdomain.more.systems ^^)

Inspired by Hackover CTF 2016:

![stats_1](https://cloud.githubusercontent.com/assets/1720809/22657975/ad12bb4e-ec98-11e6-86ae-62fd6662ebec.png)

![stats_2](https://cloud.githubusercontent.com/assets/1720809/22657986/b5debad4-ec98-11e6-981d-061db6033fda.png)

**Comment by kaydoubleu** [comment]
Though, I would suggest to introduce even more fancy graphics ;)

**Comment by stefan2904** [comment]
* graphs: https://fuzzy.land/admin/graphs
* more stats without graphs: https://fuzzy.land/admin/statistics

**Comment by stefan2904** [comment]
I think this is more like an an enhancement and should not block the october release.
