### ISSUE TITLE
Hide ansible team or teams list in general

### ISSUE THREAD

**Issue by f0rki** [LosFuzzys/CTFd#20]
see [internal discussion](https://github.com/LosFuzzys/losctf-ansible/issues/21)

**Comment by f0rki** [comment]
@stefan2904 made the point

> Maybe we can hide the teams list entirely?
> I think the scoreboard is enough (only lists teams with >0 points, also allows to hide teams.)

which I think is a good and probably quick solution

**Comment by stefan2904** [comment]
"Hiding" as in "remove the link to the team list in the navigation" should be enough.

**Comment by skogler** [comment]
Link removed from navigation in 83fc19e.
