### ISSUE TITLE
Sort challenges according to points?

### ISSUE THREAD

**Issue by f0rki** [LosFuzzys/CTFd#21]
see [internal discussion](https://github.com/LosFuzzys/losctf-ansible/issues/24)

**Comment by f0rki** [comment]
I propose sorting challenges

1. by points ascending
2. by name alphabetical

**Comment by stefan2904** [comment]
I think that sorting makes sense, except in situations like this:

![20170918_selection_03](https://user-images.githubusercontent.com/527767/30526000-9c460aa8-9c12-11e7-900b-652a53222da8.png)

(we can ignore this special case, though.)

**Comment by f0rki** [comment]
@stefan2904 yeah I also think that we should ignore this special case...

**Comment by skogler** [comment]
This behaviour should be implemented as of  f82e430
