### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by kaydoubleu** [LosFuzzys/CTFd#4]
An FAQ section might be very useful for beginners!

Url suggestion: infos.losctf-...

Inspired by Hackover CTF 2016:

![faq](https://cloud.githubusercontent.com/assets/1720809/22658293/e931aa62-ec99-11e6-8e25-bc0a85c94a99.png)

**Comment by stefan2904** [comment]
https://fuzzy.land/FAQ

**Comment by stefan2904** [comment]
Please propose questions
