### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by kaydoubleu** [LosFuzzys/CTFd#5]
URL suggestion: score.losctf-..

Inspired by Hackover CTF 2016:

![score](https://cloud.githubusercontent.com/assets/1720809/22658333/03a635fc-ec9a-11e6-9eee-9ab09ac448b0.png)

**Comment by dkales** [comment]
the plots seem to be somwhat "xkcd"-fied, maybe that would also look cool

dan.iel.fm/xkcd/

https://jakevdp.github.io/blog/2012/10/07/xkcd-style-plots-in-matplotlib/

**Comment by stefan2904** [comment]
Maybe also think about different scoreboards, like "differential scoreboard of the month", or "scoreboard per semester a student is in" or "scoreboard of a lecture"?
