### ISSUE TITLE
Welcome + News

### ISSUE THREAD

**Issue by kaydoubleu** [LosFuzzys/CTFd#6]
URL suggestion: news.losctf-...

A welcome page might be useful for people visiting the page for the first time.
Moreover, we could use this page to welcome our fellow Fuzzys and spread news :)

Inspired by Hackover CTF 2016:

![welcome](https://cloud.githubusercontent.com/assets/1720809/22658429/4fc808d4-ec9a-11e6-84f1-e091c75f2555.png)

**Comment by stefan2904** [comment]
yes, this is still open, need to think about & discuss how we want to do this ...

**Comment by stefan2904** [comment]
the mainpage of lse is also a cool idea, I think: https://ctf.lse.epita.fr/

**Comment by stefan2904** [comment]
I think this is more like an an enhancement and should not block the october release.

**Comment by stefan2904** [comment]
I added our twitter stream to the startpage as kind of news section.
(Right now only displayed if window is large enough. Need CSS wizard to fix this.)

**Comment by stefan2904** [comment]
"solved" by embedding a twitter stream.
