### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by stefan2904** [LosFuzzys/CTFd#7]
I would love to have at least one support channel.

For example, this could be a (very simple) web-forum, or a IRC channel + webirc client.
I am in strong favour of the irc channel. 

There should be a "Forum" and/or "Chat" tab in the frontend.

**Comment by f0rki** [comment]
+1 for IRC channel e.g. `#losctf`

**Comment by stefan2904** [comment]
i created #FuzzyLand on OFTC, added it to the error page (displayed if docker dies), to the *need help* challenge (including a 5pt flag in the channels topic) and the faq. is this enough?

**Comment by skogler** [comment]
I think this should be enough for now.
