### ISSUE TITLE
[Important] Link to Netcup

### ISSUE THREAD

**Issue by stefan2904** [LosFuzzys/CTFd#9]
Netcup is our sponsor

-->

"Als Gegenleistung für das Sponsoring, erwarten wir eine Verlinkung auf Ihrer Webseite entweder im Footer oder im Header."

-->

I propose something like a small logo, and/or "Supported by", " Infrastructure sponsored by", ...

and a link to netcup.de

**Comment by f0rki** [comment]
Haben wir ein Logo?

**Comment by stefan2904** [comment]
Nein, es steht im Vertrag auch nur Verlinkung und nicht Logo. Also entweder ein Logo suchen, oder Text.

**Comment by stefan2904** [comment]
link on homepage implemented
